import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.Vector;
import java.util.stream.Stream;

import javax.management.InstanceAlreadyExistsException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class CuteMorphoCompiler {

    public static void main(String[] args) throws Exception {
        emit("run");
        CuteMorphoParser yyparser = new CuteMorphoParser(new FileReader("test.s"));
        
        yyparser.yylex();
        emit(String.valueOf(yyparser.parse()));

        emit("end");        
    }

    static void emit(String s) {
        System.out.println(s);
    }
}
